### ISSUE TITLE
Update Google Maps SDK to 1.13

### ISSUE THREAD

**Issue by abouzek** [hotschedules/HSClusterMapView#3]
This seems easy, but the error:

ERROR | [iOS] Encountered an unknown error (The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/_x/w8t76b496h94vh9_ddwk8p_9bqj38w/T/CocoaPods/Lint/Pods/GoogleMaps/Frameworks/GoogleMaps.framework)) during validation.

occurs when trying to validate the podspec with Google Maps v 1.11.1.

**Comment by dluksza** [comment]
how about jumping to Google Maps 1.13?

**Comment by abouzek** [comment]
Help on this would be appreciated, as I can only work on this in small doses.

**Comment by dluksza** [comment]
My workaround for this issue was to import it into my code base then xcode stopped complaining about different maps versions

**Comment by abouzek** [comment]
The issue for me was pushing the pod to Cocoapods spec repo. I just had to pass the '--use-libraries' option to fix the issue. In order to fix the issue you describe, just run 'pod update GoogleMaps'.

**Comment by dluksza** [comment]
It doesn't work for me. When I add HSClusterMapView to my Podfile and run `pod update` I'm not able to run the app from xcode. It is complaining reading modulemap from on of the other dependencies.

As a side not I also use OpenInGoogleMap in my project and that one doesn't cause such issues.

**Comment by abouzek** [comment]
Hmm, I will look into this in the near future. I did just push version 1.0.5 which has GoogleMaps version 1.13 integrated. To be clear, the issue is with conflicting maps versions, right?

**Comment by dluksza** [comment]
Yes, this particular issue is about conflicting versions. And it is solved, thank you ;)

**Comment by abouzek** [comment]
Great 👍
